---
- name: Subscribe system and enable repos
  hosts: admin, clients
  vars_files:
    - ./vars/hosts.yml
  tasks:
  - name: Register and add rhcs repos for RHEL 8
    shell: |
           subscription-manager register --username {{ user_name }} --password='{{ password }}' --force
           subscription-manager attach --pool={{ pool }}
           subscription-manager repos --disable=*
           subscription-manager repos --enable=rhel-8-for-x86_64-baseos-rpms \
           --enable=rhel-8-for-x86_64-appstream-rpms \
           --enable=rhceph-5-tools-for-rhel-8-x86_64-rpms \
           --enable=ansible-2.9-for-rhel-8-x86_64-rpms

  - name: Install cephadm-ansible
    yum:
      name:
        - git
        - cephadm-ansible
      state: latest

- name: Running cephadm-preflight.yml
  import_playbook: cephadm-preflight.yml