user_name: 'ctorres-redhat'
password: 'put_yours'
pool: '8a85f9997acf22f9017b4e4153d762e7'
mon_node_01: 'ceph-osd-1'
mon_node_01_ip: '192.168.1.101'
registry_url: 'registry.redhat.io'
registry_user_name: '8046962|ctorres'
registry_password: 'put_yours'