service_type: host
addr: 192.168.1.101
hostname: ceph-osd-1
labels:
- mon
- osd
- mgr
---
service_type: host
addr: 192.168.1.102
hostname: ceph-osd-2
labels:
- mon
- osd
- mgr
---
service_type: host
addr: 192.168.1.103
hostname: ceph-osd-3
labels:
- mon
- osd
- mgr
---
service_type: host
addr: 192.168.1.104
hostname: ceph-osd-4
labels:
- osd
- prometheus
- grafana
---
service_type: host
addr: 192.168.1.105
hostname: ceph-osd-5
labels:
- osd
- mds
- rgw
---
service_type: host
addr: 192.168.1.106
hostname: ceph-osd-6
labels:
- osd
- mds
- rgw
---
service_type: osd
service_id: osd_spec_default
placement:
  host_pattern: '*'
---
service_type: rgw
service_id: test_realm.test_zone
placement:
  label: "rgw"
spec:
  rgw_realm: test_realm
  rgw_zone: test_zone
---
service_type: mds
service_id: cephfs
placement:
  label: "mds"